# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-05-20" # 纪念日
CITY: "北京"

BIRTHDAY:
  - "05-21"

APP_ID: "wx974f462b04e42542"
APP_SECRET: "029cb5a365547900e87a149a6b715799"

USER_ID:
  - "o9h9s5mAJsg4ndel4CcKxi-DpRmo"
  #- "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "mhYbwfAyrIPT5m4vQv7oT9C_5S-USnq9yjtxJA6x5Ms"
